---
title: "Final Project"
author: "Johann Memmel"
date: "27/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("PMCMRplus")) install.packages("PMCMRplus")
library(PMCMRplus)
if (!require("car")) install.packages("car")
library(car)
#downloads/installs packages and loads them
```


```{r}
AcuteData = read.csv("48hr acute Sodium Nitrate test mod.csv", fileEncoding="UTF-8-BOM")
#Loads the csv file
```


```{r}
boxplot(AcuteData[which(AcuteData$Time=='48'),]$Percent.Immobilized~AcuteData[which(AcuteData$Time=='48'),]$Conc, xlab="Concentration g/L", ylab = "% of organisms immobilized", col="cyan")
#Generates a boxplot of the concentration vs the percent immobilized
#figure 1
```


```{r}
x <- AcuteData[which(AcuteData$Time=='48'),]$Percent.Immobilized
g <- as.factor(AcuteData[which(AcuteData$Time=='48'),]$Conc)
#sets the variables x and g to the percent immobilized and the concentration at time = 48. This is because we are only intrested in the final results and not the results at time = 0 or time = 24

fit <- aov(x ~ g)
#fits the variables into an ANOVA
```

```{r}
summary.aov(fit)
#tests the ANOVA to show if all the means are equal. A significant results indicates that not all means are equal.
#table 1
```


```{r}
TukeyHSD(fit)
#Runs the Tukey test on the ANOVA. a p adjusted value of <0.05 indicates a significant diference
#table 2
```






```{r}
summary(dunnettTest(x, g, alternative = "greater"))
#Runs the Dunnett test. A p value of <0.05 indicates a significant diference.
#Table 3
```

```{r}
shapiro.test(fit$residuals)
#runs shapiro wilk test to determine if the residuals are normally distributed6
#Table 4

hist(fit$residuals)
#Generates a histogram to confirm shapiro wilks test result
#figure 2

qqPlot(fit$residuals)
#Generates a Q-Q plot to confirm shapiro wilks test result
#figure 3
```

```{r}
bartlett.test(x ~ g)
#table 5

leveneTest(x,g)
#table 6
#these two tests confirm that the amount of variance in each comparison group is equal
```
